name: cmragent
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch
  - torchaudio
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib-base
  - ipykernel
  - rdkit
  - langchain
  - requests
  - pyyaml
  - pip
  - mkl
  - openssl
  - ca-certificates
  - pip:
    - openai==1.56.1
    - transformers==4.47.1
    - huggingface-hub==0.27.0
    - langchain-community==0.3.9
    - langchain-experimental==0.3.3
    - chemprop==2.1.0
    - molvs==0.1.1
    - pubchempy==1.0.4
    - xgboost==2.1.3
    - seaborn==0.13.2
    - umap-learn==0.5.7
    - streamlit==1.40.2
    - flask==3.1.2
    - requests
    - tqdm==4.67.1
    - pandas-flavor==0.6.0
    - python-dotenv==1.0.1
    - pydantic==2.10.3
    - selenium
    - bs4
    - tiktoken
    - zhipuai
    - sparkai
    - spark-ai-python
    - qianfan
    - numexpr
